name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14.18.0', 18.x]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: npm install || npm install # retry once, install on windows is flaky...
    - name: Build & lint & test
      run: npm run all
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: packages/*/reports/*/test-results.xml

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    # https://github.com/ryanclark/karma-webpack/issues/494
    - name: Windows temp dir fix
      run: |
        echo TEMP="D:\Temp" >> $env:GITHUB_ENV
        echo TMP="D:\Temp" >> $env:GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: npm install || npm install # retry once, install on windows is flaky...
    - name: Build packages
      run: npm run build
    - name: Run e2e tests
      run: npm run e2e
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: e2e-reports
        path: e2e/test/*/reports/mutation/
        
  # publish-test-results:
  #   needs: build_and_test
  #   runs-on: ${{ matrix.os }}
  #   permissions:
  #     checks: write
  #     pull-requests: write
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       node-version: ['14.18.0', 18.x]
  #       os: ['ubuntu-latest', 'windows-latest']
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Download Artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: artifacts
  #     - name: Publish Test Results
  #       id: test-results
  #       uses: ./composite
  #       with:
  #         check_name: Test Results (${{ matrix.os-label }} python ${{ matrix.python }})
  #         files: "artifacts${{ steps.os.outputs.path-sep }}**${{ steps.os.outputs.path-sep }}*.xml"
  #         json_file: "tests.json"